### ISSUE TITLE
'yarn start' not functioning 

### ISSUE THREAD

**Issue by TauqeerAhmad5201** [trilitech/umami-v2#1365]
Hi maintainer, 

I'd been recently setting up the project locally and tried `yarn start` but I got an error as start not found because package.json is having no start function. 

Then I tried using `yarn dev` which was working perfectly on port 3000, and `yarn preview` on port 4173 after running `yarn build`. I believe we should be checking out the script for this. 

### Environment
Operating System: [ macOS ]
Browser: [ Brave ]

### Screenshot
<img width="1053" alt="image" src="https://github.com/trilitech/umami-v2/assets/68806440/bf46bfda-5ec2-45f1-9462-4dd062d1e1a3">

**Comment by serjonya-trili** [comment]
thanks @TauqeerAhmad5201 for the report
indeed, we had an outdated command name in the readme file.

we are migrating to a monorepo setup, and the commands will be updated too. please refer to the turbo.json and particular subproject's package.json & readme files for the available
