### ISSUE TITLE
No migration from previous version of Umami

### ISSUE THREAD

**Issue by picdc** [trilitech/umami-v2#948]
Hello,

I'm a user of Umami v1 (v0.9 to be precise). I've installed Umami V2 and it seems there are no migration from the previous version, I have to import my ledger again.

**Comment by serjonya-trili** [comment]
Hi @picdc 

If I am not mistaken, you are correct, and the backup on V1 contains only the encrypted mnemonics, so ledger & social accounts have to imported again I am afraid
