### ISSUE TITLE
Derivation path cannot be customized

### ISSUE THREAD

**Issue by picdc** [trilitech/umami-v2#949]
The previous version of Umami made it possible to customize the derivation path, especially the last part that is generally left for the user to customize.

For example in the case of `m/44'/1729'/?/k`, `k`should be customizable.

**Comment by serjonya-trili** [comment]
Hi @picdc

So, as I understand you have a default derivation path. Once you onboard, the accounts you'd see would be the ones with K=0,1,..n where n is the latest that's revealed. And you can add as many more as you'd like, the K will keep incrementing.

Does it solve your problem or you'd prefer to have just one account with K=12345 for example?
In that case I can recommend you to use the import secret key feature.

**Comment by serjonya-trili** [comment]
this has been addressed with the V2.1.0 release :)
